import type { Metadata } from "next";
import LegalShell, { type LegalSection } from "../components/legal-shell";

export const metadata: Metadata = {
  title: "Privacy Policy | HalaCX",
  description: "How HalaCX and Polinth collect, use, protect and share personal data.",
};

const sections: LegalSection[] = [
  { id: "scope", title: "Scope and responsibility", content: <><p>This Privacy Policy explains how Polinth Software Trading L.L.C. processes personal data when you visit HalaCX, create an account, request a demonstration, use our voice-agent services, or communicate with us.</p><p>When a business uses HalaCX to handle its customer calls, that business normally determines why the call data is processed. Polinth processes that data on its instructions. The business should provide its callers with any notices and choices required by applicable law.</p></> },
  { id: "data", title: "Data we collect", content: <><p>Depending on how you use HalaCX, we may collect:</p><ul><li>Account and business information, including your name, work email, company and login details.</li><li>Call information, including phone numbers, timestamps, duration, recordings, transcripts, summaries and actions taken during a call.</li><li>Configuration and knowledge-base content that you upload or connect to the service.</li><li>Technical information, including device, browser, IP address, logs and security events.</li><li>Commercial and support records, including subscription, billing and correspondence details.</li></ul></> },
  { id: "use", title: "How we use data", content: <><p>We use personal data to provide and secure HalaCX, connect and route calls, generate transcripts and summaries, perform requested workflow actions, support users, process payments, diagnose service issues and meet legal obligations.</p><p>We may also use limited account and usage information to improve the service and communicate about relevant HalaCX features. We do not sell personal data.</p></> },
  { id: "voice", title: "Voice calls and AI", content: <><p>HalaCX converts audio into text and generates responses so an AI voice agent can conduct a conversation. A customer may enable recording, transcription, analytics or integrations. Availability and use of these features must comply with the laws that apply to the customer, caller and call location.</p><p>Customers are responsible for configuring appropriate greetings, AI disclosures, recording notices, consent flows and escalation rules.</p></> },
  { id: "sharing", title: "Service providers and transfers", content: <><p>We share data only as needed with infrastructure, telephony, AI, authentication, database, analytics, support and payment providers that help operate HalaCX. We may also disclose data when required by law, to protect users or the service, or as part of a corporate transaction.</p><p>Some providers may process data outside your country. Where required, we use contractual and organisational safeguards for international transfers.</p></> },
  { id: "retention", title: "Retention and security", content: <><p>We retain personal data for as long as needed to provide the service, fulfil the purposes described here, comply with legal duties and resolve disputes. Retention can vary by data type, account settings and contractual requirements.</p><p>We use technical and organisational safeguards designed to protect data, including access controls, encryption in transit, logging and restricted production access. No service can guarantee absolute security.</p></> },
  { id: "rights", title: "Your choices and rights", content: <><p>Depending on applicable law, you may ask to access, correct, delete, restrict or receive a copy of your personal data, or object to certain processing. You may also withdraw consent where processing relies on consent.</p><p>Email <a href="mailto:privacy@polinth.com">privacy@polinth.com</a> to submit a request. We may need to verify your identity. If your data was collected by a HalaCX customer during a call, contact that business first so it can handle your request as the responsible organisation.</p></> },
  { id: "cookies", title: "Cookies and communications", content: <><p>HalaCX may use essential cookies and similar technologies for authentication, security, preferences and service operation. We may use limited analytics to understand product performance. You can control non-essential cookies through available settings and your browser.</p><p>You can unsubscribe from marketing email using the link in the message. Service and security notices may still be sent when necessary.</p></> },
  { id: "updates", title: "Updates and contact", content: <><p>We may update this policy as HalaCX, our providers or legal requirements change. We will post the revised version here and update its effective date. Material changes may also be communicated through the service or by email.</p><p>Questions or privacy requests can be sent to <a href="mailto:privacy@polinth.com">privacy@polinth.com</a>. HalaCX is operated by Polinth Software Trading L.L.C. in Dubai, United Arab Emirates.</p></> },
];

export default function PrivacyPage() {
  return <LegalShell label="HalaCX legal" title="Privacy Policy" summary="A clear account of the data HalaCX handles, why we handle it, and the controls available to you." effectiveDate="29 August 2026" sections={sections} />;
}
