import type { Metadata } from "next";
import LegalShell, { type LegalSection } from "../components/legal-shell";

export const metadata: Metadata = {
  title: "Terms of Service | HalaCX",
  description: "The terms governing access to and use of the HalaCX platform.",
};

const sections: LegalSection[] = [
  { id: "agreement", title: "Agreement and eligibility", content: <><p>These Terms govern access to and use of HalaCX, a service operated by Polinth Software Trading L.L.C. By creating an account, ordering services or using HalaCX, you agree to these Terms on behalf of yourself or the organisation you represent.</p><p>You must have legal capacity to enter this agreement. If you use HalaCX for an organisation, you confirm that you have authority to bind it.</p></> },
  { id: "service", title: "The service", content: <><p>HalaCX provides tools for configuring and operating AI voice agents, connecting telephone services and business systems, managing knowledge, and reviewing call outcomes. Features may change as the service develops.</p><p>We may provide trials, previews or beta features. These may be limited, changed or discontinued and are provided for evaluation unless we state otherwise.</p></> },
  { id: "accounts", title: "Accounts and security", content: <><p>You must provide accurate account information, protect credentials and promptly tell us about suspected unauthorised access. You are responsible for activity under your account and for managing the users and permissions in your workspace.</p><p>You may not share credentials in a way that circumvents account limits or attempt to access another customer’s workspace.</p></> },
  { id: "customer", title: "Customer responsibilities", content: <><p>You control your agent instructions, knowledge, phone numbers, integrations and use cases. You are responsible for their accuracy and legality, and for reviewing agent behaviour before production use.</p><ul><li>Provide required AI, recording and privacy notices to callers.</li><li>Obtain required permissions and consents.</li><li>Use authorised phone numbers and caller identification.</li><li>Maintain suitable human escalation and emergency procedures.</li><li>Avoid using HalaCX as the sole decision maker for high-impact decisions.</li></ul></> },
  { id: "acceptable-use", title: "Acceptable use", content: <><p>You may not use HalaCX to violate law or third-party rights, impersonate others, deceive callers about material facts, send unlawful or abusive communications, conduct fraud, facilitate harm, compromise systems, evade service limits or generate prohibited content.</p><p>We may investigate suspected misuse and restrict or suspend access when reasonably necessary to protect people, networks, providers or the service.</p></> },
  { id: "telephony", title: "Telephony and third-party services", content: <><p>Calls may rely on telecommunications carriers, number providers, AI providers and customer-selected integrations. Their availability, coverage, pricing, policies and technical performance may affect HalaCX.</p><p>You are responsible for carrier requirements, number registration, calling permissions, local calling hours and any sector-specific rules. Third-party services are governed by their own terms.</p></> },
  { id: "fees", title: "Fees and payment", content: <><p>Paid services are billed according to the order, plan or usage rates shown at purchase. Usage can include call minutes, telephone charges, AI processing and optional features. Unless stated otherwise, fees exclude taxes and carrier surcharges.</p><p>You authorise us or our payment provider to charge amounts due. Overdue amounts may result in restricted or suspended service. Subscription cancellation takes effect at the end of the current billing period unless your order states otherwise.</p></> },
  { id: "ownership", title: "Ownership and data", content: <><p>Polinth and its licensors retain all rights in HalaCX, including its software, interfaces, documentation and branding. We grant you a limited, non-exclusive, non-transferable right to use the service during your subscription.</p><p>You retain rights in content and data you provide. You grant us the rights needed to host, process, transmit and display that content to provide and secure HalaCX. Our handling of personal data is described in the Privacy Policy and any applicable data-processing agreement.</p></> },
  { id: "ai", title: "AI limitations", content: <><p>AI-generated speech, transcripts, summaries and actions may be incomplete or incorrect. You must evaluate HalaCX for your use case, test instructions and integrations, and apply human review where an error could cause material harm.</p><p>HalaCX is not an emergency service and must not be used as a replacement for emergency, medical, legal or financial professionals.</p></> },
  { id: "warranties", title: "Availability and warranties", content: <><p>We work to keep HalaCX reliable and secure, but uninterrupted or error-free operation is not guaranteed. To the extent permitted by law, the service is provided as available and without implied warranties not expressly stated in an order or written agreement.</p><p>Planned maintenance, provider outages, carrier failures and events outside our reasonable control may affect service availability.</p></> },
  { id: "liability", title: "Liability", content: <><p>To the maximum extent permitted by law, neither party is liable for indirect, incidental, special, punitive or consequential loss, or for lost profits, revenue, goodwill or data.</p><p>Polinth’s total liability arising from HalaCX will not exceed the fees paid or payable for the service during the twelve months before the event giving rise to the claim. This limit does not apply where liability cannot legally be limited.</p></> },
  { id: "termination", title: "Suspension and termination", content: <><p>You may stop using HalaCX and close your account subject to any order commitment. We may suspend or terminate access for material breach, non-payment, security risk, unlawful use or where a provider prevents us from continuing the service.</p><p>After termination, your access ends. Provisions that by their nature should survive will remain effective, including payment, ownership, confidentiality, disclaimers and liability terms.</p></> },
  { id: "general", title: "General terms", content: <><p>These Terms and any applicable order form form the agreement between you and Polinth for HalaCX. If an order conflicts with these Terms, the order controls for that conflict. You may not assign the agreement without our consent, except as part of a permitted corporate reorganisation or sale.</p><p>The agreement is governed by the laws of the United Arab Emirates as applied in the Emirate of Dubai. Courts in Dubai have exclusive jurisdiction, unless a written agreement states otherwise.</p></> },
  { id: "changes", title: "Changes and contact", content: <><p>We may update these Terms to reflect service, provider or legal changes. We will post the updated Terms and change the effective date. If a material update negatively affects your rights, we will provide reasonable notice where required.</p><p>Questions about these Terms can be sent to <a href="mailto:legal@polinth.com">legal@polinth.com</a>.</p></> },
];

export default function TermsPage() {
  return <LegalShell label="HalaCX legal" title="Terms of Service" summary="The operating rules for using HalaCX, written to be practical for teams building customer-facing voice agents." effectiveDate="29 August 2026" sections={sections} />;
}
