"use client";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { BookOpen01 as BookOpen, Calendar as CalendarDays, CheckCircle as CircleCheck, ChevronLeft, ChevronRight, Clock, File02 as FileText, Globe02 as Globe, Headphones01 as Headset, HomeLine as LayoutDashboard, Lock01 as LockKeyhole, LogOut01 as LogOut, Mail01 as Mail, Menu01 as Menu, Phone, PhoneCall01 as PhoneCall, Play, SearchLg as Search, Settings01 as Settings, Stars01 as Sparkles, Table, Waves as AudioWaveform, XClose as X } from "@untitledui/icons";
import { Avatar, Theme, Tooltip } from "@radix-ui/themes";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

type Call = { id:string; caller_name?:string; from_number?:string; to_number?:string; direction:string; status:string; outcome?:string; duration_seconds?:number; created_at:string; summary?:string; recording_url?:string; transcript?:Array<{speaker:string;start:number;end:number;text:string}> };
type DashboardData = { preview:boolean; user:{name:string}; workspace?:{name:string}; calls:Call[]; knowledge:{id:string;title:string;source_type:string;status:string;updated_at:string}[]; agent?:{name:string;status:string;languages:string[]} };
type Connector = { slug:string; name:string; description:string; status:string; accessLevel:string };

export default function DashboardApp() {
  const [data,setData]=useState<DashboardData|null>(null); const [error,setError]=useState(""); const [phone,setPhone]=useState("+971"); const [calling,setCalling]=useState(false); const [callError,setCallError]=useState(""); const [selected,setSelected]=useState<Call|null>(null); const [connectors,setConnectors]=useState<Connector[]>([]); const [connectorConfigured,setConnectorConfigured]=useState(true); const [connecting,setConnecting]=useState(""); const [connectorError,setConnectorError]=useState(""); const [query,setQuery]=useState(""); const [sidebarCollapsed,setSidebarCollapsed]=useState(false); const [mobileNavOpen,setMobileNavOpen]=useState(false); const [activeSection,setActiveSection]=useState("overview"); const router=useRouter();
  useEffect(()=>{ fetch("/api/dashboard").then(async r=>{if(!r.ok)throw new Error("Could not load workspace");return r.json()}).then(setData).catch(e=>setError(e.message)); },[]);
  useEffect(()=>{ fetch("/api/connectors").then(async r=>{if(!r.ok)return null;return r.json()}).then(body=>{if(body){setConnectors(body.connectors||[]);setConnectorConfigured(body.configured)}}); },[]);
  const stats=useMemo(()=>{const calls=data?.calls||[];const seconds=calls.reduce((sum,c)=>sum+(c.duration_seconds||0),0);return [{label:"Calls handled",value:String(calls.length),note:"This workspace"},{label:"Resolution rate",value:calls.length?`${Math.round(calls.filter(c=>c.status==="completed").length/calls.length*100)}%`:"0%",note:"Completed calls"},{label:"Talk time",value:`${Math.round(seconds/60)}m`,note:"Across all agents"}];},[data]);
  async function startCall(){setCallError("");setCalling(true);const r=await fetch("/api/calls",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({phone})});const body=await r.json();setCalling(false);if(!r.ok)setCallError(body.error);else setCallError(body.demo?"Preview call started. Add voice credentials for a real call.":"Call started. Your phone should ring now.");}
  function changePhoneCountry(code:string){setPhone(current=>code+current.replace(/^\+(?:971|91)/,""));}
  function changePhoneNumber(value:string){const code=phone.startsWith("+91")&&!phone.startsWith("+971")?"+91":"+971";setPhone(code+value.replace(/\D/g,""));}
  async function logout(){await fetch("/api/auth/logout",{method:"POST"});router.push("/");router.refresh();}
  async function openCall(call:Call){setSelected(call);const response=await fetch(`/api/calls/${call.id}`);if(response.ok){const detail=await response.json();setSelected(detail.call);}}
  async function connectTool(toolkit:string){setConnecting(toolkit);setConnectorError("");const response=await fetch("/api/connectors/connect",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({toolkit})});const body=await response.json();setConnecting("");if(!response.ok){setConnectorError(body.error||"Could not connect this app");return;}window.location.assign(body.redirectUrl);}
  function goTo(section:string){setActiveSection(section);setMobileNavOpen(false);document.getElementById(section)?.scrollIntoView({behavior:"smooth",block:"start"});}
  const connectorIcon=(slug:string)=>slug==="notion"?<FileText/>:slug==="googlecalendar"?<CalendarDays/>:slug==="gmail"?<Mail/>:slug==="googlesheets"?<Table/>:<Globe/>;
  if(error)return <main className="center-state"><h1>Workspace unavailable</h1><p>{error}</p></main>;
  if(!data)return <main className="dashboard-loading"><div/><div/><div/></main>;
  const agent=data.agent||{name:"Maya",status:"ready",languages:["English","Arabic"]};
  const normalizedQuery=query.trim().toLowerCase();
  const visibleConnectors=connectors.filter(item=>!normalizedQuery||`${item.name} ${item.description}`.toLowerCase().includes(normalizedQuery));
  const visibleCalls=data.calls.filter(call=>!normalizedQuery||`${call.caller_name||""} ${call.from_number||""} ${call.to_number||""} ${call.status} ${call.outcome||""}`.toLowerCase().includes(normalizedQuery));
  return <Theme appearance="light" accentColor="blue" grayColor="slate" radius="medium" scaling="100%" className="dashboard-theme"><main id="content" className={`dashboard-shell${sidebarCollapsed?" sidebar-collapsed":""}`}>
    {mobileNavOpen&&<button className="sidebar-scrim" aria-label="Close navigation" onClick={()=>setMobileNavOpen(false)}/>}
    <aside className={`dash-sidebar${mobileNavOpen?" mobile-open":""}`} aria-label="Workspace navigation"><div className="sidebar-brand"><Link className="wordmark wordmark-light" href="/"><span className="wordmark-mark"><AudioWaveform /></span><span>hala<strong>CX</strong></span></Link><Button variant="ghost" size="icon" className="sidebar-toggle" onPress={()=>setSidebarCollapsed(value=>!value)} aria-label={sidebarCollapsed?"Expand sidebar":"Collapse sidebar"} title={sidebarCollapsed?"Expand sidebar":"Collapse sidebar"}>{sidebarCollapsed?<ChevronRight/>:<ChevronLeft/>}</Button><Button variant="ghost" size="icon" className="sidebar-mobile-close" onPress={()=>setMobileNavOpen(false)} aria-label="Close navigation"><X/></Button></div><button className="workspace-switcher" type="button" title={data.workspace?.name||"HalaCX"}><Avatar fallback={(data.workspace?.name||"H").slice(0,1).toUpperCase()} radius="medium"/><span><small>WORKSPACE</small><strong>{data.workspace?.name||"HalaCX"}</strong></span><ChevronRight/></button><div className="sidebar-navigation"><div className="sidebar-group"><p className="sidebar-label">OPERATIONS</p><nav>{[{id:"overview",label:"Overview",icon:<LayoutDashboard/>},{id:"calls",label:"Calls",icon:<PhoneCall/>},{id:"agent",label:"Agents",icon:<Headset/>}].map(item=><button key={item.id} className={activeSection===item.id?"active":""} aria-current={activeSection===item.id?"page":undefined} title={item.label} onClick={()=>goTo(item.id)}>{item.icon}<span>{item.label}</span></button>)}</nav></div><div className="sidebar-group"><p className="sidebar-label">BUILD</p><nav>{[{id:"knowledge",label:"Knowledge",icon:<BookOpen/>},{id:"phone-number",label:"Phone numbers",icon:<Globe/>},{id:"connectors",label:"Integrations",icon:<Settings/>}].map(item=><button key={item.id} className={activeSection===item.id?"active":""} aria-current={activeSection===item.id?"page":undefined} title={item.label} onClick={()=>goTo(item.id)}>{item.icon}<span>{item.label}</span></button>)}</nav></div></div><div className="sidebar-bottom"><div className="usage"><div><span>PLAN USAGE</span><small>42 of 500 minutes</small></div><strong>8%</strong><i><b/></i></div><div className="sidebar-profile"><Avatar fallback={data.user.name.slice(0,2).toUpperCase()} radius="full"/><span><strong>{data.user.name}</strong><small>Workspace owner</small></span><Button variant="ghost" size="icon" title="Log out" onPress={logout} aria-label="Log out"><LogOut/></Button></div></div></aside>
      <section className="dash-main"><header className="dash-topbar"><Button variant="ghost" size="icon" className="mobile-menu" onPress={()=>setMobileNavOpen(true)} aria-label="Open navigation"><Menu/></Button><div><p>OVERVIEW <span>/</span> {(data.workspace?.name || "HALACX").toUpperCase()}</p><h1>Good morning, {data.user.name.split(" ")[0]}</h1><small>Here is what your voice operation is doing today.</small></div><div className="topbar-right"><label className="dashboard-search"><Search/><input aria-label="Search workspace" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search calls and integrations"/></label><Badge className="system-status" tone="success"><i/> Systems operational</Badge><Tooltip content={data.user.name}><button className="user-chip"><Avatar fallback={data.user.name.slice(0,2).toUpperCase()} radius="full"/></button></Tooltip></div></header>
      {data.preview&&<div className="preview-banner"><Sparkles/><p><strong>Product preview</strong> · Connect Supabase to turn on real accounts and persistent records.</p></div>}
      <section id="overview" className="stats-row">{stats.map(s=><article key={s.label}><span>{s.label}</span><strong>{s.value}</strong><small>{s.note}</small></article>)}<article id="agent" className="agent-status-card"><div><span className="agent-initial">M</span><i/></div><p><span>PRIMARY AGENT</span><strong>{agent.name}</strong><small>{agent.languages.join(" · ")}</small></p></article></section>
      <section className="operations-grid"><article id="phone-number" className="test-call-card"><div className="card-kicker"><span>LIVE TEST</span><i/> Agent ready</div><h2>Call yourself.<br/><em>Meet {agent.name}.</em></h2><p>Hear how your agent answers using the knowledge and rules in this workspace.</p><label>YOUR MOBILE NUMBER<div><select aria-label="Country code" value={phone.startsWith("+91")&&!phone.startsWith("+971")?"+91":"+971"} onChange={e=>changePhoneCountry(e.target.value)}><option value="+971">UAE +971</option><option value="+91">India +91</option></select><input value={phone.replace(/^\+(?:971|91)/,"")} onChange={e=>changePhoneNumber(e.target.value)} inputMode="numeric" aria-label="Mobile number without country code" placeholder="Mobile number"/><Button onPress={startCall} isDisabled={calling} loading={calling}><Phone/>{calling?"Calling…":"Call me"}</Button></div></label>{callError&&<small className="call-feedback">{callError}</small>}<div className="voice-lines">{Array.from({length:28}).map((_,i)=><i key={i} style={{height:`${8+(i*17)%35}px`}}/>)}</div></article>
        <article id="knowledge" className="knowledge-card"><header><div><BookOpen/><p><span>KNOWLEDGE BASE</span><strong>{data.knowledge.length} active sources</strong></p></div></header><div className="knowledge-readiness"><strong>{data.knowledge.length?86:0}<small>%</small></strong><p>Answer readiness<span>{data.knowledge.length?"Good coverage":"No sources connected"}</span></p></div><div className="knowledge-list">{data.knowledge.slice(0,3).map(k=><div key={k.id}><CircleCheck/><p><strong>{k.title}</strong><span>{k.source_type}</span></p><small>Active</small></div>)}</div></article></section>
      <section id="connectors" className="connector-section"><header><div><p>INTEGRATIONS</p><h2>Connected tools</h2><small>Give your agent access to approved business data during calls.</small></div><span><LockKeyhole/> Workspace scoped</span></header><div className="connector-list connector-list-standalone">{visibleConnectors.map(connector=><article key={connector.slug}><i>{connectorIcon(connector.slug)}</i><p><strong>{connector.name}</strong><span>{connector.description}</span></p><small>{connector.accessLevel === "read" ? "READ ONLY" : "READ + WRITE"}</small><button className={connector.status === "connected" ? "connected" : ""} disabled={connector.status === "connected" || connecting === connector.slug || data.preview} onClick={()=>connectTool(connector.slug)}>{connector.status === "connected"?<><CircleCheck/> Connected</>:connecting===connector.slug?"Opening…":"Connect"}</button></article>)}</div>{normalizedQuery&&visibleConnectors.length===0&&<p className="dashboard-filter-empty">No integrations match “{query}”.</p>}{!connectorConfigured&&<p className="connector-note">Integration connections are unavailable until the workspace API key is configured.</p>}{connectorError&&<p className="connector-error">{connectorError}</p>}</section>
      <section id="calls" className="calls-section"><header><div><p>CALL ACTIVITY</p><h2>Recent conversations</h2></div><span className="section-count">{visibleCalls.length} calls</span></header><div className="calls-table"><div className="table-head"><span>Caller</span><span>Direction</span><span>Time</span><span>Duration</span><span>Outcome</span><span/></div>{visibleCalls.length?visibleCalls.map(call=><button className="table-row" key={call.id} onClick={()=>openCall(call)}><span className="caller-cell"><i>{(call.caller_name||"Unknown").split(" ").map(v=>v[0]).join("").slice(0,2)}</i><b>{call.caller_name||"Unknown caller"}<small>{call.from_number||call.to_number}</small></b></span><span>{call.direction}</span><span>{new Date(call.created_at).toLocaleDateString("en-AE",{day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"})}</span><span><Clock/>{Math.floor((call.duration_seconds||0)/60)}:{String((call.duration_seconds||0)%60).padStart(2,"0")}</span><span><em>{call.outcome||call.status}</em></span><ChevronRight/></button>):<div className="empty-calls"><PhoneCall/><h3>{normalizedQuery?"No matching calls":"No calls yet"}</h3><p>{normalizedQuery?"Try another caller, number, or outcome.":"Place a test call to start building your call history."}</p></div>}</div></section>
    </section>
    {selected&&<div className="drawer-backdrop" onMouseDown={()=>setSelected(null)}><aside className="drawer" onMouseDown={e=>e.stopPropagation()}><header><div><p>CALL DETAILS</p><h2>{selected.caller_name||"Unknown caller"}</h2><span>{new Date(selected.created_at).toLocaleString("en-AE")}</span></div><button onClick={()=>setSelected(null)}><X/></button></header>{selected.recording_url?<div className="recording real-recording"><audio controls preload="none" src={`/api/calls/${selected.id}/recording`}/><span>{Math.floor((selected.duration_seconds||0)/60)}:{String((selected.duration_seconds||0)%60).padStart(2,"0")}</span></div>:<div className="recording recording-pending"><Play/><span>Recording processing</span></div>}<section className="summary"><div><Sparkles/><strong>Call summary</strong></div><p>{selected.summary||"Summary will appear when post-call analysis is complete."}</p><div className="facts"><span><small>DIRECTION</small>{selected.direction}</span><span><small>OUTCOME</small>{selected.outcome||selected.status}</span></div></section>{Boolean(selected.transcript?.length)&&<section className="call-transcript"><p>TRANSCRIPT</p>{selected.transcript!.map((line,index)=><div key={`${line.start}-${index}`}><span>{line.speaker}</span><p>{line.text}</p><time>{Math.floor(line.start/60)}:{String(Math.floor(line.start%60)).padStart(2,"0")}</time></div>)}</section>}</aside></div>}
  </main></Theme>;
}
