"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { BookOpen01, Calendar, CheckCircle, ChevronDown, ChevronLeft, ChevronRight, Clock, File02, Globe02, Headphones01, HomeLine, LinkExternal01, Lock01, LogOut01, Mail01, Menu01, Phone, PhoneCall01, Play, SearchLg, Settings01, Table, Waves, XClose } from "@untitledui/icons";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import styles from "./dashboard.module.css";

type Call = { id:string; caller_name?:string; from_number?:string; to_number?:string; direction:string; status:string; outcome?:string; duration_seconds?:number; created_at:string; summary?:string; recording_url?:string; transcript?:Array<{speaker:string;start:number;end:number;text:string}> };
type DashboardData = { preview:boolean; user:{name:string}; workspace?:{name:string}; calls:Call[]; knowledge:{id:string;title:string;source_type:string;status:string;updated_at:string}[]; agent?:{name:string;status:string;languages:string[]} };
type Connector = { slug:string; name:string; description:string; status:string; accessLevel:string };

const primaryNav=[{id:"overview",label:"Overview",icon:HomeLine},{id:"calls",label:"Calls",icon:PhoneCall01},{id:"agent",label:"Agents",icon:Headphones01}];
const buildNav=[{id:"knowledge",label:"Knowledge",icon:BookOpen01},{id:"phone-number",label:"Phone numbers",icon:Globe02},{id:"connectors",label:"Integrations",icon:Settings01}];
const initials=(name:string)=>name.split(" ").map(part=>part[0]).join("").slice(0,2).toUpperCase()||"HC";
const duration=(seconds=0)=>`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,"0")}`;

export default function DashboardApp(){
  const router=useRouter();
  const [data,setData]=useState<DashboardData|null>(null),[error,setError]=useState(""),[query,setQuery]=useState(""),[phone,setPhone]=useState("+971"),[callError,setCallError]=useState("");
  const [calling,setCalling]=useState(false),[selected,setSelected]=useState<Call|null>(null),[connectors,setConnectors]=useState<Connector[]>([]),[connectorConfigured,setConnectorConfigured]=useState(true),[connecting,setConnecting]=useState(""),[connectorError,setConnectorError]=useState("");
  const [collapsed,setCollapsed]=useState(false),[mobileOpen,setMobileOpen]=useState(false),[active,setActive]=useState("overview");
  useEffect(()=>{fetch("/api/dashboard").then(async response=>{if(!response.ok)throw new Error("Could not load workspace");return response.json();}).then(setData).catch(reason=>setError(reason.message));},[]);
  useEffect(()=>{fetch("/api/connectors").then(async response=>response.ok?response.json():null).then(body=>{if(body){setConnectors(body.connectors||[]);setConnectorConfigured(body.configured);}});},[]);
  const stats=useMemo(()=>{const calls=data?.calls||[],seconds=calls.reduce((sum,call)=>sum+(call.duration_seconds||0),0);return [{label:"Total calls",value:String(calls.length),note:"All conversations",icon:PhoneCall01},{label:"Completed",value:calls.length?`${Math.round(calls.filter(call=>call.status==="completed").length/calls.length*100)}%`:"0%",note:"Resolution rate",icon:CheckCircle},{label:"Talk time",value:`${Math.round(seconds/60)}m`,note:"Across all agents",icon:Clock}];},[data]);
  const normalizedQuery=query.trim().toLowerCase(),visibleCalls=(data?.calls||[]).filter(call=>!normalizedQuery||`${call.caller_name||""} ${call.from_number||""} ${call.to_number||""} ${call.status} ${call.outcome||""}`.toLowerCase().includes(normalizedQuery)),visibleConnectors=connectors.filter(item=>!normalizedQuery||`${item.name} ${item.description}`.toLowerCase().includes(normalizedQuery));
  function goTo(id:string){setActive(id);setMobileOpen(false);document.getElementById(id)?.scrollIntoView({behavior:"smooth",block:"start"});}
  function changeCountry(code:string){setPhone(current=>code+current.replace(/^\+(?:971|91)/,""));}
  function changeNumber(value:string){const code=phone.startsWith("+91")&&!phone.startsWith("+971")?"+91":"+971";setPhone(code+value.replace(/\D/g,""));}
  async function logout(){await fetch("/api/auth/logout",{method:"POST"});router.push("/");router.refresh();}
  async function startCall(){setCallError("");setCalling(true);try{const response=await fetch("/api/calls",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({phone})}),body=await response.json();setCallError(response.ok?(body.demo?"Preview call started. Add voice credentials for a real call.":"Call started. Your phone should ring now."):(body.error||"Could not start the call."));}finally{setCalling(false);}}
  async function openCall(call:Call){setSelected(call);const response=await fetch(`/api/calls/${call.id}`);if(response.ok){const body=await response.json();setSelected(body.call);}}
  async function connectTool(toolkit:string){setConnecting(toolkit);setConnectorError("");const response=await fetch("/api/connectors/connect",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({toolkit})}),body=await response.json();setConnecting("");if(!response.ok){setConnectorError(body.error||"Could not connect this app");return;}window.location.assign(body.redirectUrl);}
  function connectorIcon(slug:string){const Icon=slug==="notion"?File02:slug==="googlecalendar"?Calendar:slug==="gmail"?Mail01:slug==="googlesheets"?Table:Globe02;return <Icon/>;}
  if(error)return <main className={styles.state}><h1>Workspace unavailable</h1><p>{error}</p></main>;
  if(!data)return <main className={styles.loading}><span/><span/><span/></main>;
  const agent=data.agent||{name:"Maya",status:"ready",languages:["English","Arabic"]};
  const navigation=(compact=false)=><>{[{title:"Workspace",items:primaryNav},{title:"Configure",items:buildNav}].map(group=><div className={styles.navGroup} key={group.title}><p>{group.title}</p>{group.items.map(({id,label,icon:Icon})=><button key={id} className={active===id?styles.active:""} aria-current={active===id?"page":undefined} title={label} onClick={()=>goTo(id)}><Icon/><span className={compact?styles.srOnly:""}>{label}</span></button>)}</div>)}</>;
  return <main className={`${styles.shell} ${collapsed?styles.collapsed:""}`}>
    {mobileOpen&&<button className={styles.scrim} aria-label="Close navigation" onClick={()=>setMobileOpen(false)}/>}
    <aside className={`${styles.sidebar} ${mobileOpen?styles.mobileOpen:""}`} aria-label="Primary navigation"><div className={styles.brandRow}><Link href="/" className={styles.brand}><span><Waves/></span>{!collapsed&&<b>hala<i>CX</i></b>}</Link><Button variant="ghost" size="icon" className={styles.collapseButton} onPress={()=>setCollapsed(value=>!value)} aria-label={collapsed?"Expand sidebar":"Collapse sidebar"}>{collapsed?<ChevronRight/>:<ChevronLeft/>}</Button><Button variant="ghost" size="icon" className={styles.closeButton} onPress={()=>setMobileOpen(false)} aria-label="Close navigation"><XClose/></Button></div><button className={styles.workspace} title={data.workspace?.name||"HalaCX"}><span>{(data.workspace?.name||"H")[0].toUpperCase()}</span>{!collapsed&&<><div><small>Current workspace</small><strong>{data.workspace?.name||"HalaCX"}</strong></div><ChevronDown/></>}</button><nav className={styles.navigation}>{navigation(collapsed)}</nav><div className={styles.sidebarFooter}>{!collapsed&&<div className={styles.usage}><div><span>Monthly usage</span><strong>42 / 500 min</strong></div><small>8%</small></div>}<div className={styles.profile}><span>{initials(data.user.name)}</span>{!collapsed&&<div><strong>{data.user.name}</strong><small>Workspace owner</small></div>}<Button variant="ghost" size="icon" onPress={logout} aria-label="Log out" title="Log out"><LogOut01/></Button></div></div></aside>
    <section className={styles.app}><header className={styles.topbar}><div className={styles.heading}><Button variant="ghost" size="icon" className={styles.menuButton} onPress={()=>setMobileOpen(true)} aria-label="Open navigation"><Menu01/></Button><div><span>{data.workspace?.name||"HalaCX"}</span><h1>Overview</h1></div></div><div className={styles.topActions}><label className={styles.search}><SearchLg/><input value={query} onChange={event=>setQuery(event.target.value)} aria-label="Search workspace" placeholder="Search workspace"/></label><Badge tone="success" className={styles.status}>All systems operational</Badge><button className={styles.avatar} title={data.user.name}>{initials(data.user.name)}</button></div></header>
      <div className={styles.content}>{data.preview&&<div className={styles.preview}><strong>Preview workspace</strong><span>Connect Supabase to enable persistent records.</span></div>}<section id="overview" className={styles.welcome}><div><h2>Good morning, {data.user.name.split(" ")[0]}</h2><p>Monitor calls, manage your agent, and keep customer conversations moving.</p></div><Button onPress={()=>goTo("phone-number")}><Phone/>Test your agent</Button></section>
        <section className={styles.metrics}>{stats.map(({label,value,note,icon:Icon})=><article key={label}><div><span>{label}</span><Icon/></div><strong>{value}</strong><small>{note}</small></article>)}<article id="agent" className={styles.agentCard}><div className={styles.agentHead}><span>{agent.name[0]}</span><Badge tone="success">Ready</Badge></div><div><small>Primary agent</small><strong>{agent.name}</strong><p>{agent.languages.join(", ")}</p></div><Button variant="secondary" size="sm" onPress={()=>goTo("connectors")}>Manage agent</Button></article></section>
        <section className={styles.mainGrid}><article id="phone-number" className={styles.callPanel}><header><div><span>Live test</span><h2>Call your agent</h2><p>Enter your number to hear how the current agent handles a real conversation.</p></div><div className={styles.voiceMark}><Waves/></div></header><label>Mobile number<div className={styles.phoneField}><select value={phone.startsWith("+91")&&!phone.startsWith("+971")?"+91":"+971"} onChange={event=>changeCountry(event.target.value)} aria-label="Country code"><option value="+971">UAE +971</option><option value="+91">India +91</option></select><input value={phone.replace(/^\+(?:971|91)/,"")} onChange={event=>changeNumber(event.target.value)} inputMode="numeric" aria-label="Mobile number" placeholder="50 123 4567"/><Button onPress={startCall} loading={calling}><Phone/>{calling?"Calling":"Call me"}</Button></div></label>{callError&&<p className={styles.feedback}>{callError}</p>}</article><article id="knowledge" className={styles.knowledge}><header><div><BookOpen01/><span><small>Knowledge</small><strong>{data.knowledge.length} active sources</strong></span></div><Button variant="ghost" size="icon" aria-label="Open knowledge"><ChevronRight/></Button></header>{data.knowledge.length?<div className={styles.sourceList}>{data.knowledge.slice(0,3).map(source=><div key={source.id}><File02/><span><strong>{source.title}</strong><small>{source.source_type}</small></span><Badge tone="success">Active</Badge></div>)}</div>:<div className={styles.empty}><BookOpen01/><strong>No knowledge connected</strong><p>Add company information so your agent can answer accurately.</p><Button variant="secondary" size="sm">Add source</Button></div>}</article></section>
        <section id="connectors" className={styles.section}><div className={styles.sectionHeader}><div><h2>Integrations</h2><p>Connect the systems your agent can use during calls.</p></div><Badge tone="neutral"><Lock01/> Workspace scoped</Badge></div><div className={styles.integrations}>{visibleConnectors.map(connector=><article key={connector.slug}><span className={styles.integrationIcon}>{connectorIcon(connector.slug)}</span><div><strong>{connector.name}</strong><p>{connector.description}</p></div><small>{connector.accessLevel==="read"?"Read only":"Read and write"}</small><Button variant="secondary" size="sm" isDisabled={connector.status==="connected"||connecting===connector.slug||data.preview} onPress={()=>connectTool(connector.slug)}>{connector.status==="connected"?<><CheckCircle/>Connected</>:connecting===connector.slug?"Opening":"Connect"}</Button></article>)}</div>{normalizedQuery&&visibleConnectors.length===0&&<p className={styles.filterEmpty}>No integrations match “{query}”.</p>}{!connectorConfigured&&<p className={styles.note}>Integration connections require a configured workspace API key.</p>}{connectorError&&<p className={styles.error}>{connectorError}</p>}</section>
        <section id="calls" className={styles.section}><div className={styles.sectionHeader}><div><h2>Recent calls</h2><p>Review outcomes, recordings, and conversation details.</p></div><Badge tone="neutral">{visibleCalls.length} calls</Badge></div><div className={styles.table}><div className={styles.tableHead}><span>Caller</span><span>Status</span><span>Date</span><span>Duration</span><span/></div>{visibleCalls.length?visibleCalls.map(call=><button className={styles.callRow} key={call.id} onClick={()=>openCall(call)}><span className={styles.caller}><i>{initials(call.caller_name||"Unknown")}</i><b>{call.caller_name||"Unknown caller"}<small>{call.from_number||call.to_number}</small></b></span><span><Badge tone={call.status==="completed"?"success":"neutral"}>{call.outcome||call.status}</Badge></span><span>{new Date(call.created_at).toLocaleDateString("en-AE",{day:"numeric",month:"short",year:"numeric"})}</span><span>{duration(call.duration_seconds)}</span><ChevronRight/></button>):<div className={styles.emptyCalls}><PhoneCall01/><strong>{normalizedQuery?"No matching calls":"No calls yet"}</strong><p>{normalizedQuery?"Try a different search.":"Place a test call to start your call history."}</p></div>}</div></section>
      </div></section>
    {selected&&<div className={styles.drawerBackdrop} onMouseDown={()=>setSelected(null)}><aside className={styles.drawer} onMouseDown={event=>event.stopPropagation()}><header><div><span>Call details</span><h2>{selected.caller_name||"Unknown caller"}</h2><p>{new Date(selected.created_at).toLocaleString("en-AE")}</p></div><Button variant="ghost" size="icon" onPress={()=>setSelected(null)} aria-label="Close details"><XClose/></Button></header>{selected.recording_url?<audio controls preload="none" src={`/api/calls/${selected.id}/recording`}/>:<div className={styles.processing}><Play/>Recording processing</div>}<section><h3>Summary</h3><p>{selected.summary||"The summary will appear after post-call analysis is complete."}</p><div className={styles.facts}><span><small>Direction</small><strong>{selected.direction}</strong></span><span><small>Outcome</small><strong>{selected.outcome||selected.status}</strong></span><span><small>Duration</small><strong>{duration(selected.duration_seconds)}</strong></span></div></section>{Boolean(selected.transcript?.length)&&<section><h3>Transcript</h3><div className={styles.transcript}>{selected.transcript!.map((line,index)=><div key={`${line.start}-${index}`}><strong>{line.speaker}</strong><p>{line.text}</p><time>{duration(Math.floor(line.start))}</time></div>)}</div></section>}<Link href="#calls" className={styles.externalLink}>View call activity <LinkExternal01/></Link></aside></div>}
  </main>;
}
